# Generated by Django 5.0.14 on 2025-04-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_subscriber_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': ' دنبال کنندگان خبرنامه', 'verbose_name_plural': ' دنبال کنندگان خبرنامه'},
        ),
    ]
