# Generated by Django 5.1.5 on 2025-03-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count_product',
            field=models.CharField(default=0, max_length=100, unique=True),
        ),
    ]
