# Generated by Django 5.1.5 on 2025-03-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_count_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='count_product',
            field=models.IntegerField(default=0),
        ),
    ]
