# Generated by Django 5.1.5 on 2025-03-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_count_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('main_price', models.IntegerField(default=100)),
                ('discount_price', models.IntegerField(default=100)),
            ],
        ),
    ]
