# Generated by Django 5.1.5 on 2025-03-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_newproducts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproducts',
            name='discount_price',
            field=models.CharField(default=100, max_length=100),
        ),
        migrations.AlterField(
            model_name='newproducts',
            name='main_price',
            field=models.CharField(default=100, max_length=100),
        ),
    ]
