# Generated by Django 5.1.5 on 2025-03-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_newproducts_discount_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewWeBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='weblog_image/')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
