# Generated by Django 5.1.5 on 2025-03-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproducts',
            name='discount_price',
            field=models.IntegerField(default=100, max_length=100),
        ),
        migrations.AlterField(
            model_name='newproducts',
            name='main_price',
            field=models.IntegerField(default=100, max_length=100),
        ),
    ]
