# Generated by Django 5.1.5 on 2025-03-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_newproducts_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproducts',
            name='discount_price',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='newproducts',
            name='main_price',
            field=models.IntegerField(default=100000),
        ),
    ]
