# Generated by Django 5.1.5 on 2025-03-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_newproducts_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproducts',
            name='discount_price',
            field=models.IntegerField(default=100000, verbose_name='قیمت محصول با تخفیف'),
        ),
        migrations.AlterField(
            model_name='newproducts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='عکس محصول'),
        ),
        migrations.AlterField(
            model_name='newproducts',
            name='main_price',
            field=models.IntegerField(default=100000, verbose_name='قیمت اصلی محصول'),
        ),
        migrations.AlterField(
            model_name='newproducts',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم محصول'),
        ),
    ]
