# Generated by Django 5.1.5 on 2025-03-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_newproducts_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproducts',
            name='caption',
            field=models.CharField(default='Hello this is a text', max_length=500, unique=True, verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newproducts',
            name='quality',
            field=models.CharField(default='درجه یک', max_length=300, unique=True, verbose_name='کفیفت'),
        ),
        migrations.AddField(
            model_name='newproducts',
            name='weight',
            field=models.CharField(default='1 کیلوگرم ، 750 گرم ، 500 گرم', max_length=400, unique=True, verbose_name='وزن'),
        ),
    ]
