# Generated by Django 5.1.5 on 2025-03-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_newproducts_caption_alter_newproducts_quality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproducts',
            name='caption',
        ),
    ]
