# Generated by Django 5.1.5 on 2025-03-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_newproducts_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproducts',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='newproducts',
            name='weight',
        ),
    ]
