# Generated by Django 5.1.5 on 2025-03-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_newproducts_quality_remove_newproducts_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproducts',
            name='Description',
            field=models.CharField(default='توضیحات', max_length=500, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='newproducts',
            name='quality',
            field=models.CharField(default='درجه یک', max_length=300, verbose_name='کفیفت'),
        ),
        migrations.AddField(
            model_name='newproducts',
            name='weight',
            field=models.CharField(default='1 کیلوگرم ، 750 گرم ، 500 گرم', max_length=400, verbose_name='وزن'),
        ),
    ]
