# Generated by Django 5.1.5 on 2025-03-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_newproducts_description_newproducts_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproducts',
            name='Description',
            field=models.TextField(default='توضیحات', max_length=500, verbose_name='توضیحات'),
        ),
    ]
