# Generated by Django 5.1.5 on 2025-03-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_newproducts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproducts',
            name='Short_description',
            field=models.TextField(default='توضیحات', max_length=800, verbose_name='توضیحات کوتاه در مورد مصحول '),
        ),
        migrations.AlterField(
            model_name='newproducts',
            name='Description',
            field=models.TextField(default='توضیحات', max_length=1000, verbose_name='توضیحات'),
        ),
    ]
