# Generated by Django 5.1.5 on 2025-03-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_newproducts_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newweblog',
            name='short_description',
            field=models.TextField(default='short description', max_length=200, verbose_name='توضیح کوتاه در مورد موضوع '),
        ),
        migrations.AlterField(
            model_name='newweblog',
            name='description',
            field=models.TextField(default='long description', max_length=1000, verbose_name='توضیحات در مورد موضوع'),
        ),
    ]
