# Generated by Django 5.1.5 on 2025-03-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل مدیریت')),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل پشتیبانی')),
                ('management_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس مدیریت')),
                ('support_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس پشتیبانی')),
                ('landline_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن ثابت')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='واتساپ')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='تلگرام')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='توییتر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس',
            },
        ),
    ]
