# Generated by Django 5.1.5 on 2025-03-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_productcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('street', models.CharField(max_length=255, verbose_name='آدرس خیابان')),
                ('postal_code', models.CharField(max_length=20, verbose_name='کد پستی')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('products', models.TextField(verbose_name='محصولات (نام، تعداد و قیمت)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ کل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
            ],
        ),
    ]
