# Generated by Django 5.1.5 on 2025-04-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_billinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproducts',
            name='category',
            field=models.TextField(default='خرما', max_length=500, verbose_name='دسته بندی محصول'),
        ),
    ]
