# Generated by Django 5.0.14 on 2025-04-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_newproducts_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billinginfo',
            options={'verbose_name': ' سفارش های ثبت شده ', 'verbose_name_plural': ' سفارش های ثبت شده '},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی محصولات ', 'verbose_name_plural': ' دسته بندی محصولات '},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'ارتباط با ما ', 'verbose_name_plural': 'ارتباط با ما '},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'اطلاعات تماس ادمین ', 'verbose_name_plural': 'اطلاعات تماس ادمین'},
        ),
        migrations.AlterModelOptions(
            name='newproducts',
            options={'verbose_name': ' محصولات جدید', 'verbose_name_plural': ' محصولات جدید '},
        ),
        migrations.AlterModelOptions(
            name='newweblog',
            options={'verbose_name': ' مطالب جدید', 'verbose_name_plural': ' مطالب جدید'},
        ),
        migrations.AlterModelOptions(
            name='productcomment',
            options={'verbose_name': ' دیدگاه مرتبط به محصولات ', 'verbose_name_plural': ' دیدگاه مرتبط به محصولات'},
        ),
    ]
