# Generated by Django 5.0.14 on 2025-04-09 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_billinginfo_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproducts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category'),
        ),
    ]
