# Generated by Django 5.0.14 on 2025-04-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_newproducts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='e', unique=True),
            preserve_default=False,
        ),
    ]
