# Generated by Django 5.1 on 2025-03-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
